name: Test Rest Assured
on: push
jobs:
  test:
    runs-test: windows-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v3
      - name: run test
        run: mvn test

